import type { CSSProperties } from "react";

/** Co-located styles for the Project Context page. */
export const s = {
  page: { padding: "24px 32px 44px", maxWidth: 1200, margin: "0 auto" } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 14, marginBottom: 18 } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  searchWrap: { marginBottom: 12, maxWidth: 420 } satisfies CSSProperties,
  banner: {
    marginBottom: 14,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg, var(--bg-elevated))",
    color: "var(--text-primary)",
    fontSize: 12.5,
  } satisfies CSSProperties,
  // Two columns once a document is selected; a single, wider column otherwise.
  layout: (split: boolean): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: split ? "360px 1fr" : "1fr",
    gap: 20,
    alignItems: "start",
  }),
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    listStyle: "none",
    padding: 0,
    margin: 0,
    maxHeight: "calc(100vh - 320px)",
    overflow: "auto",
  } satisfies CSSProperties,
  card: { cursor: "pointer" } satisfies CSSProperties,
  cardSelected: { cursor: "pointer", border: "1px solid var(--accent)" } satisfies CSSProperties,
  row: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  icon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  path: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  preview: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    minHeight: 200,
  } satisfies CSSProperties,
  previewHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
    paddingBottom: 12,
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  previewPath: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)", flex: 1, minWidth: 0 } satisfies CSSProperties,
  previewEmpty: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 200,
    border: "1px dashed var(--border)",
    borderRadius: 8,
    color: "var(--text-muted)",
    fontSize: 13,
  } satisfies CSSProperties,
  footer: { marginTop: 16, fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
