import type { CSSProperties } from "react";

/** Co-located styles for the Onboarding Tour page. */
export const s = {
  page: { padding: "24px 32px 44px", maxWidth: 1200, margin: "0 auto" } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 18,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  subtitle: { marginTop: 6, fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  headerActions: { display: "flex", alignItems: "center", gap: 10, position: "relative" } satisfies CSSProperties,
  confirmBadge: {
    position: "absolute",
    top: "100%",
    right: 0,
    marginTop: 6,
    fontSize: 12,
    color: "var(--ok)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  errorBanner: {
    marginBottom: 14,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    color: "var(--text-primary)",
    fontSize: 12.5,
  } satisfies CSSProperties,
  loadingList: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,

  // ---- full-tour layout: TOC sidebar + section cards ----
  layout: {
    display: "grid",
    gridTemplateColumns: "220px 1fr",
    gap: 24,
    alignItems: "start",
  } satisfies CSSProperties,
  toc: {
    position: "sticky",
    top: 16,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  tocHeading: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  tocList: { display: "flex", flexDirection: "column", gap: 2, listStyle: "none", padding: 0, margin: 0 } satisfies CSSProperties,
  tocItem: (active: boolean): CSSProperties => ({
    display: "block",
    width: "100%",
    textAlign: "left",
    padding: "6px 10px",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: active ? 650 : 500,
    color: active ? "var(--text-primary)" : "var(--text-secondary)",
    background: active ? "var(--bg-hover)" : "transparent",
    borderLeft: active ? "2px solid var(--accent)" : "2px solid transparent",
  }),
  sections: { display: "flex", flexDirection: "column", gap: 14, minWidth: 0 } satisfies CSSProperties,

  // ---- section card ----
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    overflow: "hidden",
  } satisfies CSSProperties,
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "13px 16px",
    textAlign: "left",
    background: "transparent",
    fontSize: 14.5,
    fontWeight: 650,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  cardIndex: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 20,
    height: 20,
    borderRadius: "50%",
    background: "var(--bg-hover)",
    color: "var(--text-muted)",
    fontSize: 11,
    fontWeight: 700,
    flexShrink: 0,
  } satisfies CSSProperties,
  cardTitle: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  chevron: { flexShrink: 0, color: "var(--text-muted)", transition: "transform .12s" } satisfies CSSProperties,
  cardBody: {
    padding: "0 16px 16px",
    borderTop: "1px solid var(--border)",
    paddingTop: 14,
    fontSize: 13.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,

  // ---- link / command rows ----
  linkList: { display: "flex", flexDirection: "column", gap: 8, listStyle: "none", padding: 0, margin: "10px 0 0" } satisfies CSSProperties,
  linkRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "8px 10px",
    borderRadius: 6,
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  linkText: { display: "flex", flexDirection: "column", gap: 2, minWidth: 0 } satisfies CSSProperties,
  linkPath: {
    fontSize: 12.5,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  linkLabel: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  openLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12.5,
    color: "var(--accent-text)",
    flexShrink: 0,
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  commandRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "8px 10px",
    borderRadius: 6,
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  commandMain: { display: "flex", flexDirection: "column", gap: 2, minWidth: 0 } satisfies CSSProperties,
  commandText: {
    fontSize: 12.5,
    color: "var(--text-primary)",
    overflowWrap: "break-word",
  } satisfies CSSProperties,
  commandSource: { fontSize: 11.5, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
